language: xslt
install:
- echo "Installed"
script:
- sh .travis/publish.sh
after_success:
- sh .travis/deploy.sh
env:
  global:
  - TITLE="Sample DITA Wiki"
  - WELCOME="DITA magic with GitHub and oXygen"
  - TEMPLATE="aquamarine"
notifications:
  email:
    on_success: always
